### ISSUE TITLE
Not an issue but..

### ISSUE THREAD

**Issue by karinakozarova** [Staxed/30Days30Sites-Main#1]
Is there some repository where we can see your 30sites 😄

**Comment by Staxed** [comment]
I have a "staxed" branch in this repo where I will be keeping my log.  The sites themselves are located in my portfolio repo:

https://github.com/Staxed/staxed.github.io/tree/master/30Days30Sites

**Comment by Staxed** [comment]
update: just moved my log over to a new repo to keep it completely separate.  My sites themselves will still remain in my portfolio repo.

https://github.com/Staxed/30Days30Sites
